### ISSUE TITLE
Lots of guest lists

### ISSUE THREAD

**Issue by bymayo** [verbb/wishlist#1]
### Description

Since installing the plugin yesterday we've had 401 lists created, but only 14 of these are attributed to a user account.

How is this possible when the "add to wishlist" buttons are not available to guest users.

Is it likely the controller is being hit from somewhere else (Spam?) as the IP address for most of the lists starts with `157.` or `141.`

**Comment by RyanRoberts** [comment]
We're having the same problem, hundreds of empty wishlists are being generated and I'm struggling to figure out why.

**Comment by engram-design** [comment]
@bymayo @RyanRoberts On both counts, are any calls to the Wishlist plugin, list or items available to guests? As soon as you are trying to show a users' list, it'll either fetch the users list (if logged in), fetch a guest via their user session, or create a new list based on the session.

**Comment by bymayo** [comment]
@engram-design I just checked and the add to wishlist link is publicly visible. But, for us we don't want this so we will hide the link.

This still kind of doesn't fix the problem, if we did want to have guest access.

**Comment by engram-design** [comment]
Its largely unavoidable to a degree - a new list has to be created for a new session for guests. Its why we've added `purgeInactiveLists` (https://verbb.io/craft-plugins/wishlist/docs/get-started/configuration) to hopefully help in culling these lists before they get too out of hand. We could potentially add some spam-protection via throttling. I can just see the scenario where this might prevent new lists from being created for a guest, causing more frustration.

**Comment by bymayo** [comment]
Ahhh I didn't realise there was a `purgeInactiveLists` setting. Does this fire as a task?

**Comment by engram-design** [comment]
@bymayo Nope, its a single query though, so it should be fairly instantaneous. Just note I've pushed [1.0.4](https://github.com/verbb/wishlist/releases/tag/1.0.4) with a slight fix on this.

**Comment by chadcrowell** [comment]
For the record, I have a site that I will call a medium sized size (maybe 5000 entries/content), content-wise that just borked my vps because over the last 6 months I've amassed almost 2 million rows in these tables: content, elements, elements_sites, searchIndex, and......... wishlist_lists. You really may want to set purgeInactiveLists to true by default Josh, and also set it to true in your default wishlist.php config file template for devs. I can't even run garbage collection right now because there's so much to process. Had to make a scratch file and copy your purgeInactiveLists service functions and refreshing that page over and over and over purging 35K at a time...

**Comment by engram-design** [comment]
I suppose I’m hesitant to make anything that potentially effects content on by default. But then again, I can certainly see how things can get out of hand otherwise.

I’m more than happy to change the defaults here, just hoping it won’t upset people.

**Comment by engram-design** [comment]
Also, and not sure if it’s possible for your setup, but can you force garbage collection from the command line on your server?

**Comment by chadcrowell** [comment]
The scratch file element queries allowed me to get the rows in wishlist_lists from 2 million to 2400. I think the rest should clear out tomorrow as my settings for the purge are 1 day. There should be about 150 wishlists. Once that was done and my elements, elements_sites, content, and wishlist_lists tables were down to normal row count, I was able to run garbage collection without it timing out. All good now and I'll keep an eye on it.

**Comment by engram-design** [comment]
@chadcrowell `purgeInactiveLists` is now on by default as of [1.2.12](https://github.com/verbb/wishlist/releases/tag/1.2.12)

**Comment by j-greig** [comment]
I'm still having problems purging the lists, even if I set `purgeInactiveGuestListsDuration` to something like `PT01S` and then run `./craft gc` there are millions of lists which aren't being deleted... is there a note somewhere of how to safely delete these manually via MySQ?

**Comment by j-greig** [comment]
> Had to make a scratch file and copy your purgeInactiveLists service functions and refreshing that page over and over and over purging 35K at a time...

Could you share your approach for this @chadcrowell , and (excuse the noob question) what's a scratch file?

**Comment by engram-design** [comment]
I wouldn't advise dropping these items from the database, purely because they will only delete the list record, and not the linked element.

Strange how the GC command isn't working, my testing shows its acting as expected.

I may have to put together a console command or similar for cleaning these lists up.

**Comment by engram-design** [comment]
@j-greig Wondering if you can try a new console command.

To get this early, change your `verbb/wishlist` requirement in `composer.json` to:

```
"require": {
  "verbb/wishlist": "dev-craft-3 as 1.2.15",
  "...": "..."
}
```

Then run `composer update`, and then try to run `./craft wishlist/lists/purge-inactive-lists`.

**Comment by adamgarscadden** [comment]
Hi @engram-design the first time I ran this it did 6400 which is great. But it's still missing out most of the inactive lists / items (there's over 1,000,000) is there anything else you could do to make it more sensitive. Or any flags I can add so it picks up the inactive lists? Anything over 30 days would be ideal.

**Comment by engram-design** [comment]
So I think I may know the issue here. The purge action only removes lists that are empty. Judging from your screenshots, it looks like while these lists are old, and haven't been updated, they still contain items.

I'm a little unsure if I want this to be default behaviour, as its destructive. But, I can also see the benefit in "not caring" for scenarios like yours, which is more important.

I've added `purgeEmptyListsOnly` and `purgeEmptyGuestListsOnly` config settings, which are set to true by default, to keep existing behaviour. Turning these to false should really empty out your lists/items/elements based solely on their `dateUpdated` value. As such, you might want to adjust your duration options you've been testing with, otherwise they will affect legitimate lists.

Please see [1.2.16](https://github.com/verbb/wishlist/releases/tag/1.2.16)

Closing for now as I think this should address this properly.
