### ISSUE TITLE
Migrating from Upvote Plugin

### ISSUE THREAD

**Issue by whoisjuan** [verbb/wishlist#22]
Any suggestion on what would be the best way to migrate from Upvote (https://github.com/doublesecretagency/craft-upvote)

Upvote uses this three tables to save their records: 

- craft_upvote_elementtotals
- craft_upvote_userhistories
- craft_upvote_votelog

I want to migrate to Wishlist without losing existing vote records. Their upvote_userhistories table look like this:

![image](https://user-images.githubusercontent.com/1447283/58717300-c6bef780-837f-11e9-92f2-a3c79b30bb0d.png)

Where ID is the userId as definef in Craft and the object in the second column has all the upvoted element IDs.

The question is: how can I move this data to Wishlist records?  Any suggestions? I was thinking on writing a script that goes over the upvote data and creates the records by using the Wishlist API, but I'm not sure how to pass the userId since from the documentation examples it seems this is inferred.

Any hints on this would be highly appreciated.

**Comment by engram-design** [comment]
I'm not familiar at all with the inner workings of Upvote, but I would assume they store votes as elements. If so, they should be directly compatible with Wishlist (to a degree).

The issue with Wishlist is that it stores the userId on the list, not on the individual vote. This is because Upvote wouldn't have a concept of 'lists' which group 'votes'. You would need to create a list, linked with each userId, and use that when creating your upvotes.

**Comment by engram-design** [comment]
Added in [1.3.0](https://github.com/verbb/wishlist/releases/tag/1.3.0)

**Comment by whoisjuan** [comment]
This is sick! Thanks @engram-design
