### ISSUE TITLE
initialising new list for guest

### ISSUE THREAD

**Issue by tidy** [verbb/wishlist#25]
I'm using wishlist for guests (no member login on site) and want to fetch the current list id, or generate a new one.

I'm using the following code to get the guest's current list, but it returns undefined if they have no list:
`{% set list = craft.wishlist.lists().default(true).one() %}`

I thought the reason that so many empty guest lists build up is that once the wishlist functions are used, a new list is auto generated if it doesn't already exist. But calling the lists method as above does not seem to do this.

Calling the item method before this with a dummy id does create a new list, and then craft.wishlist.lists() will always return an id:
`{% set item = craft.wishlist.item(1) %}`

Is this the correct approach or should I be using different parameters in the lists method to return a new list id if none exists, or perhaps a different function?

Thanks for your time.

**Comment by engram-design** [comment]
A new list is only created when you interact with it - by adding items to a list. Fetching it in this manner won't create a new default list automatically. So its working as expected - otherwise, there'll be too much overhead in calling list functions to check if it exists, etc.

However, in [1.1.0](https://github.com/verbb/wishlist/releases/tag/1.1.0), you can do: `craft.wishlist.lists(true, true)` which will force a list to be created when this is called. See [docs](https://verbb.io/craft-plugins/wishlist/docs/template-guides/available-variables)
