### ISSUE TITLE
Issue with new purge-inactive-lists feature

### ISSUE THREAD

**Issue by adamgarscadden** [verbb/wishlist#54]
### Description
Running the feature only purges a small amount of the inactive lists (6000 out of 1,000,000).

### Steps to reproduce

1. Run purge command on a database with a large number of wishlists

### Additional info

- Plugin version: dev-craft-3 as 1.2.15
- Craft version: 3.4.17.1

**Comment by j-greig** [comment]
Hi @engram-design could you possibly help us figure out a manual approach to deleting these?

As per Adam's comment the new purge command is only deleting a few thousand items initially, and then a few extra each time you re-run the command. (It was 4 extra when I tried yesterday, and 20 extra on each run of the command today).

For example in terms of a manual approach, what if we...

1. Emptied the `craft_wishlist_lists` table
2. Emptied the `craft_wishlist_items` table
3. Deleted all rows from `craft_elements` where "itemFieldLayoutID" matches the one for our list type at craft_wishlist_listtypes (we only have 1 list type anyway!)

Here are some screenshots of the various tables in case it helps. The Craft/Commerce install itself has around 40 pages, 1000 products and 200 orders.

![image](https://user-images.githubusercontent.com/616194/89625942-8c5cbe80-d890-11ea-883b-1e82ba7ff01d.png)

**Comment by engram-design** [comment]
If any of you are willing to share your database, I'd be happy to sort this out properly. My testing shows that it's clearing things correctly, but maybe there's something wrong going on with the query - or there's something else at play that's site-specific.

Just let me know on Discord (crawf) if you're up for sharing.

I'll keep testing on my end, but would love to fix this up for you, as its an issue that's been around for some time.

**Comment by engram-design** [comment]
So I think I may know the issue here. The purge action only removes lists that are empty. Judging from your screenshots, it looks like while these lists are old, and haven't been updated, they still contain items.

I'm a little unsure if I want this to be default behaviour, as its destructive. But, I can also see the benefit in "not caring" for scenarios like yours, which is more important.

I've added `purgeEmptyListsOnly` and `purgeEmptyGuestListsOnly` config settings, which are set to true by default, to keep existing behaviour. Turning these to false should really empty out your lists/items/elements based solely on their `dateUpdated` value. As such, you might want to adjust your duration options you've been testing with, otherwise they will affect legitimate lists.

Please see [1.2.16](https://github.com/verbb/wishlist/releases/tag/1.2.16)

Closing for now as I think this should address this properly.
