### ISSUE TITLE
Action Update - Allow Anonymous 

### ISSUE THREAD

**Issue by BrandonJamesBorders** [verbb/wishlist#58]
**What are you trying to do?**
The website I'm building has an anonymous wishlist functionality. Trying to update it does not work as the update action is not listed in the `$allowAnonymous` variable.  

**What's your proposed solution?**
Add `update` to the allowed anonymous 

**Additional context**
Not sure of any negative side-effects of this, but as the logic in this route is protected by permission configuration I can't think of any.

**Comment by engram-design** [comment]
Yep, my only concern with this is the potential abuse on updating lists by other parties. Like delete and clear, we need to add in checks that the owner trying to update their list is the owner. Otherwise, anyone can mess around with anyone's lists.

Added in [1.2.18](https://github.com/verbb/wishlist/releases/tag/1.2.18)
