### ISSUE TITLE
optionsSignature Null Constraint

### ISSUE THREAD

**Issue by leigeber** [verbb/wishlist#61]
**Description**

When trying to update we get an exception about null values on existing rows since the migration includes notNull() on the new optionsSignature column.

**Additional info**
- Plugin version: 1.3.0
- Craft version: 3.5.12.1
- Multi-site: No

**Comment by engram-design** [comment]
Is this an error during the migration updates? If so, can you post the full error? Or, is this after the migrations have run and you're trying to update an item?

I've just rolled back a site to ensure the `notNull()` directive doesn't mess things up, but the migration does populate all rows with empty data as well. But it seems strange that is _does_ work, logically adding a new column that can't have null values would throw an error.

In any case, I think this should be fixed in [1.3.1](https://github.com/verbb/wishlist/releases/tag/1.3.1) where a bit more care is give to this.

**Comment by leigeber** [comment]
Sorry, didn't catch the full error before working around it. It was on the migration update and for what it's worth it was PostgreSQL which may be the variable. Update looks good, Thanks Josh.

**Comment by engram-design** [comment]
I was just about to ask if it was Postgres, I should get into the habit of testing that more often. This update should be a bit more robust at least
