### ISSUE TITLE
Combine duplicate items in wishlist

### ISSUE THREAD

**Issue by russback** [verbb/wishlist#64]
**What are you trying to do?**
If a user adds the same product to their wishlist, it would be useful to increase the quantity rather than add a duplicate. 

**What's your proposed solution?**
A core quantity item on the Item could be used and a duplicate could be considered to be true if the element and the passed option fields all match. The same as Craft Commerce really.

**Comment by engram-design** [comment]
Potentially, there's no real concept of "quantity" for a wishlist item, as that would require a reasonable refactor is how things work. Mostly because we're not always dealing with products. The current behaviour allows add/remove toggling, not quantity changes.

I think this is something you could achieve yourself with a custom field on the item, determining whether the item is already in a list, and if so, update the item instead of trying to add or remove it.

The `allowDuplicates` config setting also controls duplicate behaviour.

**Comment by russback** [comment]
OK, will look at a plugin or module method hooked to `Item::EVENT_BEFORE_SAVE`. I think a core quantity would be useful though, given so much of the plugin concerns support for commerce and moving from the list to the cart.
