### ISSUE TITLE
Remove from wishlist on order confirmation

### ISSUE THREAD

**Issue by russback** [verbb/wishlist#66]
**What are you trying to do?**
1. User creates a list and shares with a recipient.
2. Recipient adds to cart and opts to remove from the wishlist.
3. Recipient fails to checkout.
4. User no longer has the removed items on their wishlist.

In this scenario, the user still wants the items but no longer has them on their list.

**What's your proposed solution?**
Amend the option to remove on 'add to cart' so that it triggers on order completion rather than add to basket.

**Comment by engram-design** [comment]
There's some things to consider here. What if the wishlist is sent to multiple people, who checkout at vastly different times (maybe days later) which successful checkout should clear the list - both?

Related to this, what happens if the recipient doesn't action purchasing until weeks later where changes have continued to be made on the wishlist. It will remove any and all items in that wishlist.

I think these issues are specific to your scenario, where the wishlist seems to be shared to different people (who aren't the original owners).

**Comment by russback** [comment]
In my view that's exactly why you would want to clear a list once it has been paid for - to avoid multiple purchases of the same item. The clearance could happen at an item level rather than a list level.

I would say the second is just something to accept, an edge case.

On the last point, I'm not sure why you would share it if not with someody else?

**Comment by engram-design** [comment]
I'm going to park this one indefinitely, sorry. I think it's a pretty complex issue now I've started looking into it.

The real tricky thing is that as users can have multiple wishlists on their account or session, it's impossible to know which list to clear once checkout has been completed, as line items contain no reference to the original list they were created from.

I would say to discourage the use of `removeFromList` so that items are kept in their wishlist - just in case they don't go ahead with the purchase.
