### ISSUE TITLE
Wishlist Plugin Loads Empty Blocks Multiple Times Against User

### ISSUE THREAD

**Issue by chandamotiyani** [verbb/wishlist#70]
Version Info:
Craft CMS Version: 3.5.15.1
Wishlist Plugin: 1.4.3

The wishlist section is behaving weirdly:
/wishlist/lists/p6 - screen short is attached it shows 0 items multiple times against each user unnecessarily 

![Screen Shot 2021-01-07 at 1 36 55 pm](https://user-images.githubusercontent.com/16190427/103847646-aecd5f00-50f0-11eb-8d23-db619745ee7a.png)

In User details under wishlist the name of the logged in user is apearing instead of the user whose details are being viewed.
Multiple blank entries are coming for the wishlist section too. please find attachment - Go to the Login to Admin Panel --> Users --> Detail of User --> Under Wishlist tab

![Screen Shot 2021-01-07 at 2 05 52 pm](https://user-images.githubusercontent.com/16190427/103848341-1041fd80-50f2-11eb-9c49-73c58a2f9df6.png)

The query is that why multiple times the same user is listed with 0 items in wishlist! If the signed in user or guest user hasn't added anything in the wishlist then why does the records are being shown multiple times! Or even if they added anything then why does it appear multiple times!

Attaching more screenshots to elaborate!
![Screen Shot 2021-01-07 at 2 20 31 pm](https://user-images.githubusercontent.com/16190427/103848974-8eeb6a80-50f3-11eb-8a86-ca60842535f7.png)

![Screen Shot 2021-01-07 at 1 36 55 pm](https://user-images.githubusercontent.com/16190427/103849354-60ba5a80-50f4-11eb-8467-bfa4888d669f.png)

**Comment by engram-design** [comment]
I just wanted to triple check - are you _sure_ you're on 1.4.3? Showing your wishlists in all user accounts was fixed in 1.4.3 for instance, and I confirm this is working on my end.

As for the duplicate empty lists, are you able to look in your `wishlist_lists` db table and look at the most recently created lists? Are they all by the same user, or different users - guests in your case.

For a busy site, it's not uncommon for lots of lists to be created for each user, even if there are no items added to them. It _shouldn't_ be happening anymore until users add items to their list. But multiple lists for the same user certainly shouldn't be happening.

**Comment by chandamotiyani** [comment]
@engram-design our site is not that busy and also we are using the 1.4.3 version and the screenshots I have attached are of the live site and multiple wishlists are there against for a single user as you are saying that it's fixed but doesn't seem like to!

You can have a look at another file I have attached here showing the live site version - confirming 1.4.3

<img width="1037" alt="Screen Shot 2021-01-20 at 5 43 44 pm" src="https://user-images.githubusercontent.com/16190427/105140033-0d5df880-5b47-11eb-8322-d24b58662ff4.png">

Looks like there is still a bug can you please confirm (However, you said that you checked on your end)
I'm sending our wishlist_lists table to you email address!

**Comment by engram-design** [comment]
Thanks, that screenshot shows the plugin store, not the actual installed plugin and version. I can't replicate the behaviour you're seeing with seeing other wishlists' on a users account, but this was fixed in a recent version. I just want to make 100% sure you're on the latest version.

I've also fixed a bug where lists were being created for guests, which is probably the bug causing this issue.

To get this fix early, change your `verbb/wishlist` requirement in `composer.json` to:

```
"require": {
  "verbb/wishlist": "dev-craft-3 as 1.4.3",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Should be fixed in [1.4.4](https://github.com/verbb/wishlist/releases/tag/1.4.4)

**Comment by chandamotiyani** [comment]
@engram-design first of all thank you so very much for fixing this.. really appreciate it :ok_hand::ok_hand:

**Comment by chandamotiyani** [comment]
@engram-design 

TEST 1
- add products to wishlist as guest
- join as an insider
- the products you had added to wishlist as a guest should still be in your wishlist after signing up
- discounts should show
TEST 2
- log in as an existing user; do you still have products in your wishlist

TEST 2 is not working in both versions of the wishlist plugin 1.4.3 and 1.4.4

**Comment by engram-design** [comment]
I'm not sure I follow your second test explanation.

Do you mean you add items to the wishlist as a guest, then login as an existing user, and the wishlist items you added as a guest no longer appear in the wishlist?

**Comment by chandamotiyani** [comment]
No, I add items as a guest user and sign up then I'm able to see the items post login in my wish list but when I logout and re-login back again wish list is empty. Even If I add items as a logged-in user and logout and re-login back again wishlist is empty again.

**Comment by engram-design** [comment]
Right, moving this to a new issue: https://github.com/verbb/wishlist/issues/73

**Comment by engram-design** [comment]
@chandamotiyani Refer to my response in https://github.com/verbb/wishlist/issues/73 and follow up there.
