### ISSUE TITLE
All entries being marked 'saved' or somehow added to global wishlist?

### ISSUE THREAD

**Issue by j-greig** [verbb/wishlist#71]
**Description**
A Commerce website is experiencing a weird behaviour whereby every product is marked as liked/saved to your wishlist, even for non-logged in users it looks like.

I haven't got any more specifics on the issue as yet, just posting the issue in case anyone else has seen something similar...

**Steps to reproduce**
1. Wait....
2. Eventually something seems to overload the DB and all products show as added to your wishlist (even if you're not a logged in user, I think)

**Additional info**
- Plugin version: 1.4.3
- Craft version: Craft CMS 3.5.17.1, Commerce 3.2.13.2
- Multi-site: No

**Additional context**
Running the ./craft command to purge wishlists seems to fix the problem. The screenshot shows the "before" — running the purge command removed 8,000+ wishlists and fixed the issue. I'm needing to run the command about once a week at the moment.

![image](https://user-images.githubusercontent.com/616194/104298856-616c3b80-54bc-11eb-93d4-98b7a9dab193.png)

**Comment by engram-design** [comment]
Does this happen for all users? As in, right now, are all your users' lists full of all your products, or just some users?

Can you also confirm items are populated in the CP - just to double check there's not something with your front-end going awry?

**Comment by j-greig** [comment]
These are sensible questions, I will check next time and let you know! (thanks as ever)

**Comment by peteeveleigh** [comment]
I had this exact problem on a site that had been working fine for over year.
Suddenly all items were favourited.
Turned out to be because I wasn't explicitly calling the list for the specific user and it seemed to be loading and merging ALL lists ever created (I think). Consequently everything was favourited.

I had to do this in my base template

`{% set favourites = craft.wishlist.lists(true, true) %}`

The first 'true' parameter restricts the loaded list to the current user (even if they are a guest)

And then the bit where I show the favourite/unfavourite toggle I have this

```

{% set wishlistitem = craft.wishlist.item(propertyId) %}
		{% if wishlistitem.inList %}
			<a rel="nofollow" id="listing-favourite-{{ propertyId }}" class="property-listing__favourite js-favourite"  href="{{ wishlistitem.removeUrl() }}" data-addurl="{{ wishlistitem.addUrl() }}" data-removeurl="{{ wishlistitem.removeUrl() }}" aria-label="Remove from favourites" data-ref="{{ refCode }}"><i class="fas fa-heart property__like--liked"></i></a>
		{% else %}
			<a rel="nofollow" id="listing-favourite-{{ propertyId }}" class="property-listing__favourite js-favourite"  href="{{ wishlistitem.addUrl() }}" data-addurl="{{ wishlistitem.addUrl() }}" data-removeurl="{{ wishlistitem.removeUrl() }}" aria-label="Add to favourite" data-ref="{{ refCode }}"><i class="far fa-heart"></i></a>
		{% endif %}
```
'scuse the extra data attributes, they are just for some javascript stuff

No idea why it used to work and then suddenly didn't but it does seem to be something related to a recent change in either the plugin or in Craft itself.

**Comment by engram-design** [comment]
Thanks for the feedback @fantasticmachine what were you using for `craft.wishlist.lists()` previously? There is a warning about this and omitting the first parameter - `Setting this to false will fetch items for any user, so be careful`.

Note also you're forcing a list to be created whenever this page is loaded. If that's intentional, that's fine, but I'd ensure that's behind a login wall or similar, otherwise every visitor will have a list created on page-load.

@j-greig Maybe if you can share the templating you're using - is it a similar scenario to @fantasticmachine ?

**Comment by peteeveleigh** [comment]
@engram-design Yes I'm going to have to take another look at it tbh.

I was originally handling the favourites like so, **with no other call to create a wishlist.** It just seemed to work (for quite some time too):

```
{% macro favouritesLinks(propertyId, refCode) %}
	{% set wishlistitem = craft.wishlist.item(propertyId) %}
	{% if wishlistitem.inList %}
		<a rel="nofollow" id="listing-favourite-{{ propertyId }}" class="property-listing__favourite js-favourite"  href="{{ wishlistitem.removeUrl() }}" rel="nofollow" data-addurl="{{ wishlistitem.addUrl() }}" data-removeurl="{{ wishlistitem.removeUrl() }}" aria-label="Remove from favourites" data-ref="{{ refCode }}"><i class="fas fa-heart property__like--liked"></i></a>
	{% else %}
		<a rel="nofollow" id="listing-favourite-{{ propertyId }}" class="property-listing__favourite js-favourite"  href="{{ wishlistitem.addUrl() }}" rel="nofollow" data-addurl="{{ wishlistitem.addUrl() }}" data-removeurl="{{ wishlistitem.removeUrl() }}" aria-label="Add to favourite" data-ref="{{ refCode }}"><i class="far fa-heart"></i></a>
	{% endif %}
{% endmacro %}
```

I've actually just done a quick test **without** doing this in my layout template.
```
{% set favourites = craft.wishlist.lists(true, true) %}

```

But then when a guest user visits the site, ALL items are already favourited. The only way I can get this to work is to create the  wishlist using the tag above. Are you saying that this will create a NEW list for every page load regardless of the user already having a list for their session?

We want guests to be able to create lists, so is there a way we can only create a list once they click a favourite button?

**Comment by engram-design** [comment]
@fantasticmachine Think I've figured out what's going on here. You shouldn't need to even include a `craft.wishlist.lists` call here, but things weren't working correctly.

If you can check out [1.4.4](https://github.com/verbb/wishlist/releases/tag/1.4.4) I think it might address this.

And also in this new version, nothing happens with a list or items until the user interacts with the thing you want to add to a wishlist. There should be no more auto-creation of lists or items.
