### ISSUE TITLE
Query list items by if the product is availableForPurchase

### ISSUE THREAD

**Issue by codyjames** [verbb/wishlist#79]
**What are you trying to do?**
I'm hoping to create two views in someones list. One for things that are still available, and another for things that are no longer available for purchase.

**What's your proposed solution?**
I'd like to be able to query items by availableForPurchase. Perhaps like: `{% set items = list.items.availableForPurchase(true) %}`

**Comment by engram-design** [comment]
This won't likely be implemented, purely because it assumes all items in a wishlist are products. What happens if we try to run this query against entries? What if there are some entries and some products in the list? 

It makes it impossible to construct a query which won't fail - for instance, try running `craft.entries.availableForPurchase(true).all()` which is pretty much what we'd be trying to implement.

**Comment by codyjames** [comment]
Sounds good to me! I can write some code to do it on my end for sure.
